
units: sampleSheets/Cpyg_samples.tsv        #tab separeted files containing samplenames(sample) and path_to_reads (fq)
#Cpar_samples.tsv
#Calibrachoa_samples.tsv

### Definition of the path Snakemake has to create
working_dir: "temp/"
result_dir: "results/"

refs:
    transcriptomeFas:
        "ftp://ftp.solgenomics.net/genomes/Petunia_axillaris/annotation/Petunia_axillaris_v1.6.2_proteins.fasta"
        #"https://www.arabidopsis.org/download_files/Proteins/Araport11_protein_lists/Araport11_genes.201606.pep.fasta.gz"

adapters: "adapters.fasta"

trimmomatic:
  adapters: "adapters.fasta"
  seedMisMatches: '2'
  palindromeClipTreshold: '30'
  simpleClipThreshold: '10'
  LeadMinTrimQual: '3'
  TrailMinTrimQual: '3'
  windowSize: '4'
  avgMinQual: '15'
  minReadLength: '40'
  phred: "-phred33" # phred: for illumina >1.8 the quality score are encoded by phred33

trinity:
  seqType    : "fq"
  libType    : "R"
  cpu         : "10"
  minLength   : "200"
  maxMemory   : "20G"
  outDir   : "trinity"   # name of output directory, needs to contain trinity

blast:
  evalue     : "1e-10"
  outFmt     : "6 qseqid evalue length mismatch salltitles"   # 6 for tab separeted file.
  numThreads : "4" 
  maxTargets : "1"